spring.application.name=TekkieStoreCapstone

spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/tekkiestore_db?sslMode=VERIFY_IDENTITY&useUnicode=true&characterEncoding=utf8
spring.datasource.username=2Hq9uUcv1XQhb1H.root
spring.datasource.password=kaWqFVCZevV4uOoM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
 

# Cloudinary Configuration (3rd-Party Media Integration)
cloudinary.cloud-name=nuivwupa
cloudinary.api-key=477249257479995
cloudinary.api-secret=sCDDOSxRy3sBcLLhs8bQrtzjAcQ
 
# JWT Authentication Configuration
jwt.secret=TekkieStoreCapstoneSecureJwtKeyForSigningTokensMustBe256BitsLong2026!
jwt.expiration=86400000
