spring.application.name=TekkieStoreCapstone

spring.datasource.url= jdbc:mysql://localhost:3306/Tekkie_Store_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
 
# Cloudinary Configuration (3rd-Party Media Integration)
cloudinary.cloud-name=nuivwupa
cloudinary.api-key=477249257479995
cloudinary.api-secret=sCDDOSxRy3sBcLLhs8bQrtzjAcQ
